server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bang?useOldAliasMetadataBehavior=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&autoReconnectForPools=true&tinyInt1isBit=false&connectTimeout=3000&allowMultiQueries=true
    username: root
    password: 123